# const ----------------
# 日本地図の初期位置
ZOOM_LEVEL_4  = {
    'ZOOM': 4,
    'X_INITIALIZE_MIN': 13,
    'X_INITIALIZE_MAX': 14,
    'Y_INITIALIZE_MIN': 5,
    'Y_INITIALIZE_MAX': 6,
}

ZOOM_LEVEL_5  = {
    'ZOOM': 5,
    'X_INITIALIZE_MIN': 27,
    'X_INITIALIZE_MAX': 29,
    'Y_INITIALIZE_MIN': 11,
    'Y_INITIALIZE_MAX': 13,
}

ZOOM_LEVEL_6  = {
    'ZOOM': 6,
    'X_INITIALIZE_MIN': 54,
    'X_INITIALIZE_MAX': 57,
    'Y_INITIALIZE_MIN': 24,
    'Y_INITIALIZE_MAX': 27,
}

ZOOM_LEVEL_7  = {
    'ZOOM': 7,
    'X_INITIALIZE_MIN': 109,
    'X_INITIALIZE_MAX': 113,
    'Y_INITIALIZE_MIN': 49,
    'Y_INITIALIZE_MAX': 53,
}

ZOOM_SCOP = [
    ZOOM_LEVEL_4,
    ZOOM_LEVEL_5,
    ZOOM_LEVEL_6,
    ZOOM_LEVEL_7
]